portal/urls.py
from django.conf.urls import patterns, include, url

from base_forms.auth import UserPasswordResetForm

urlpatterns = patterns('portal.views',
    url(r'^active-calls/$', 'active_calls_view'),
    url(r'^active-calls/list/$', 'active_calls_list_view'),
    url(r'^authorized-ips/add/$', 'userauthip_create_view'),
    url(r'^authorized-ips/(?P<pk>\d+)/$', 'userauthip_update_view'),
    url(r'^authorized-ips/(?P<pk>\d+)/delete/$', 'userauthip_delete_view'),
    url(r'^billing/', include('billing.urls')),
    url(r'^cdrs/', include('cdr.urls')),
    url(r'^dids/$', 'did_list_view'),
    url(r'^dids/(?P<pk>\d+)/$', 'did_update_view'),
    url(r'^dids/export/$', 'did_export_view'),
    url(r'^dids/purchase/$', 'did_purchase_view'),
    url(r'^dids/purchase/area_codes.json$', 'did_json_view'),
    url(r'^dids/purchase/list/(?P<prefix>\d+)/$', 'did_prefix_view'),
    url(r'^dids/search/$', 'did_search_view'),
    url(r'^email-change/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<emailb64>[0-9A-Za-z=]+)-(?P<token>.+)/$',
        'email_change_confirm'),
    url(r'^interconnection/$', 'interop_view'),
    url(r'^login-history/$', 'loginhistory_list_view'),
    url(r'^pbx/$', 'pbxacct_list_view'),
    url(r'^pbx/add/$', 'pbxacct_create_view'),
    url(r'^pbx/(?P<pk>\d+)/edit/$', 'pbxacct_update_view'),
    url(r'^pbx/(?P<pk>\d+)/delete/$', 'pbxacct_delete_view'),
    url(r'^preferences/$', 'userprofile_update_view'),
    url(r'^profile/$', 'dashboard_view'),
    url(r'^service-location/$', 'serviceaddress_list_view'),
    url(r'^service-location/add/$', 'serviceaddress_create_view'),
    url(r'^service-location/(?P<pk>\d+)/edit/$', 'serviceaddress_update_view'),
    url(r'^service-location/(?P<pk>\d+)/delete/$', 'serviceaddress_delete_view'),
    url(r'^endpoint/$', 'endpoint_list_view'),
    url(r'^endpoint/add/$', 'endpoint_create_view'),
    url(r'^endpoint/(?P<pk>\d+)/edit/$', 'endpoint_update_view'),
    url(r'^web-hosting/$', 'cpanelacct_list_view'),
    url(r'^web-hosting/add/$', 'cpanelacct_create_view'),
    url(r'^web-hosting/(?P<pk>\d+)/edit/$', 'cpanelacct_update_view'),
    url(r'^web-hosting/(?P<pk>\d+)/delete/$', 'cpanelacct_delete_view')
)

urlpatterns += patterns('base_views.auth',
    url(r'^login/$', 'login'),
    url(r'^login/popup/$', 'login', {'template_name':'login_snippet.html'}),
    url(r'^logout/$', 'logout', {'next_page':'/'}),
    url(r'^password-change/$', 'password_change'),
    url(r'^password-change/done/$', 'password_change_done'),
    url(r'^password-reset/$', 'password_reset',
                                {'password_reset_form':UserPasswordResetForm,
                                 'from_email':'no-reply@5ninesolutions.com'}),
    url(r'^password-reset/done/$', 'password_reset_done'),
    url(r'^password-reset/complete/$', 'password_reset_complete'),
    url(r'^password-reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'password_reset_confirm'),
)

urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

from web.views import (DomainFormView, SupportFormView)

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'web.views.index_view'),
    url(r'^about/$', 'web.views.about_view'),
    url(r'^about/network/$', 'web.views.network_view'),
    url(r'^accounts/', include('portal.urls')),
    url(r'^admin/', include('admin.urls')),
    url(r'^contact/$', 'web.views.contact_view'),
    url(r'^contact/done/$', 'web.views.contact_done_view'),
    url(r'^cdr/import/$', 'cdr.views.cdr_import'),
    url(r'^cnam/(?P<number>[2-9]\d\d[2-9]\d{6})/$', 'cnam.views.query'),
    url(r'^crm/phone-lookup/(?P<number>\d{11,16})/$', 'cnam.views.cust_lookup'),
    url(r'^domains/check/', DomainFormView.as_view()),
    url(r'^fax/', include('fax.urls')),
    url(r'^fs-xml/', include('fs_xml_curl.urls')),
    url(r'^kb/', include('kb.urls')),
    url(r'^legal/terms-of-use/$',
        TemplateView.as_view(template_name='terms.html')),
    url(r'^legal/privacy/$',
        TemplateView.as_view(template_name='privacy.html')),
    url(r'^rates/', include('rating.urls')),
    url(r'^services/$', 'web.views.services_view'),
    url(r'^voip-pbx-hosting/$', 'web.views.pbx_service_view'),
    url(r'^web-hosting/$', 'web.views.hosting_service_view'),
    url(r'^sip-trunking/$', 'web.views.services_trunking_view'),
    url(r'^signup/', include('web.registration_urls')),
    url(r'^support/$', SupportFormView.as_view()),
    url(r'^sitemap\.xml$', 'web.views.sitemap_view'),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('',
    url(r'^kb\.php$', RedirectView.as_view(url='/kb/')),
    url(r'^helpdesk\.php$', RedirectView.as_view(url='/support/')),
    url(r'^cart\.php$', RedirectView.as_view(url='/')),
    url(r'^index\.php$', RedirectView.as_view(url='/')),
    url(r'^transcheck\.php$', RedirectView.as_view(url='/')),
    url(r'^aLogin\.php$', RedirectView.as_view(url='/accounts/login/')),
    url(r'^LostPassword\.php$', RedirectView.as_view(url='/accounts/password-reset/')),
    url(r'^contact\.php$', RedirectView.as_view(url='/contact/')),
    url(r'^terms\.php$', RedirectView.as_view(url='/legal/terms-of-use/')),
    url(r'^support\.php$', RedirectView.as_view(url='/support/')),
    url(r'^check\.php$', RedirectView.as_view(url='/web-hosting/')),
    url(r'^hosting\.php$', RedirectView.as_view(url='/web-hosting/')),
    url(r'^forsale\.php$', RedirectView.as_view(url='/web-hosting/')),
    url(r'^hsignup\.php$', RedirectView.as_view(url='/signup/')),
    url(r'^createacct\.php$', RedirectView.as_view(url='/signup/')),
    url(r'^network\.php$', RedirectView.as_view(url='/about/network/')),
)

web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from portal.models import UserProfile
from utils import pywhois


class ContactForm(forms.Form):
    PH = {'name': "Enter your name",
          'username': "Enter your username",
          'email': "Enter your email address",
          'subject': "Subject",
          'message': "Comments" }

    name = forms.CharField(max_length=100,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['name']}))
    username = forms.CharField(max_length=64, required=False,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['username']}))
    email = forms.EmailField(label="E-mail", max_length=75,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['email']}))
    subject = forms.CharField(max_length=100,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['subject']}))
    message = forms.CharField(
                widget=forms.Textarea(attrs={'class':'add-ph',
                                             'placeholder':PH['message']}))


class SupportForm(ContactForm):
    PH = {'subject': "Brief description of your support request",
          'message': "Include as much detail as possible" }

    subject = forms.CharField(max_length=100,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['subject']}))

    message = forms.CharField(
                widget=forms.Textarea(attrs={'class':'add-ph',
                                             'placeholder':PH['message']}))

    def clean_username(self):
        """
        Validates that a user exists with the given username.
        """
        username = self.cleaned_data["username"]
        self.users_cache = User.objects.filter(username__iexact=username)
        if not len(self.users_cache) > 0:
            raise forms.ValidationError("That username is not on file.")
        return username


class HostingForm(forms.Form):
    PH = {'first_name': "First Name",
          'last_name': "Last Name",
          'email': "Email Address",
          'phone': "Phone Number",
          'comments': "Comments"}

    first_name = forms.CharField(max_length=30,
                 widget=forms.TextInput(attrs={'class':'add-ph',
                                               'placeholder':PH['first_name']}))
    last_name = forms.CharField(max_length=30,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['last_name']}))
    email = forms.EmailField(label="E-mail", max_length=75,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['email']}))
    phone = forms.CharField(max_length=16,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['phone']}))
    comments = forms.CharField(
                widget=forms.Textarea(attrs={'class':'add-ph',
                                             'placeholder':PH['comments']}))


class QuoteForm(forms.Form):

    SIZE_CHOICES = (
        ('', 'Company Size'),
        ('1-4', 'Less than 5'),
        ('5-10', '5-10'),
        ('11-20', '11-20'),
        ('21-50', '21-50'),
        ('51-250', '51-250'),
        ('250+', '250+'),
        ('Unknown', 'Unknown'),
    )

    PH = {'first_name': "First Name",
          'last_name': "Last Name",
          'email': "Email Address",
          'phone': "Phone Number"}

    first_name = forms.CharField(max_length=30,
                 widget=forms.TextInput(attrs={'class':'add-ph',
                                               'placeholder':PH['first_name']}))
    last_name = forms.CharField(max_length=30,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['last_name']}))
    email = forms.EmailField(label="E-mail", max_length=75,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['email']}))
    phone = forms.CharField(max_length=16,
                widget=forms.TextInput(attrs={'class':'add-ph',
                                              'placeholder':PH['phone']}))
    company_size = forms.ChoiceField(choices=SIZE_CHOICES)


class DomainForm(forms.Form):

    domain = forms.CharField()

    def clean_domain(self):
        """
        Validates that a registered domain does not exist for the give domain
        """
        domain = self.cleaned_data["domain"]
        try:
            whois = pywhois.whois(domain)
        except pywhois.parser.PywhoisError:
            return domain
        raise forms.ValidationError("The domain %s is already registered." % domain)


class TermsOfServiceForm(forms.Form):

    tos = forms.BooleanField(widget=forms.CheckboxInput(),
                             label=u'I have read and agree to the Terms of Service',
                             error_messages={'required': "You must agree to the terms to register"})



class UserRegistrationForm(forms.Form):
    """
    A form that creates a user, with no privileges, from the given username and password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }

    first_name = forms.RegexField(label="First Name", max_length=30, regex=r'^[a-zA-Z]+$')
    last_name = forms.RegexField(label="Last Name", max_length=30, regex=r'^[a-zA-Z]+$')

    username = forms.RegexField(label=_("Username"), max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text = _("Required. 30 characters or fewer. Letters, digits and "
                      "@/./+/-/_ only."),
        error_messages = {
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text = _("Enter the same password as above, for verification."))

    email = forms.EmailField(label="E-mail", max_length=75)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def clean_email(self):
        """
        Validates that a user does not exist with the given e-mail address.
        """
        email = self.cleaned_data["email"]
        self.users_cache = User.objects.filter(
                                email__iexact=email
                            )
        if len(self.users_cache) > 0:
            raise forms.ValidationError("That e-mail address is already on file.")
        return email


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ["acct_type"]

templates/portal/active_calls.html
{% extends "base_site.html" %}
{% block title %}Active Calls{% endblock %}
{% block content_title %}Active Calls{% endblock %}
{% block content %}
<h1>Current active calls for your account</h1>
<div id="active-calls">
</div>
{% endblock %}

{% block extra_js %}<script src="{{ STATIC_URL }}js/active_calls.js"></script>{% endblock %}

templates/portal/cpanelacct_form.html
{% extends "base_site.html" %}
{% block extrastyle %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/marketing.css" />
<style type="text/css">
div.form-row { margin-bottom: 12px; }
.form-row textarea,
.form-row input[type="text"],
.form-row input[type="password"],
.form-row select {
    width: 400px;
    padding: 2px 4px;
    border: 1px solid #4f4e4e;
}

#content .container form p { margin: 0 0 16px; }
</style>
{% endblock %}

{% block title %}{% if object %}Manage{% else %}Add{% endif %} Web Hosting Account{% endblock %}

{% block content_title %}{% if object %}Manage{% else %}Add{% endif %} Web Hosting Account{% endblock %}
{% block content %}

<form action="" method="post">{% csrf_token %}
{% include "form_snippet.html" %}
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/portal/cpanelacct_list.html
{% extends "base_site.html" %}

{% block title %}Web Hosting Accounts{% endblock %}

{% block content_title %}Web Hosting Accounts{% endblock %}
{% block content %}
<a href="add/">Add New</a>
{% if cpanelacct_list %}
<table>
    <caption>Web Hosting Accounts</caption>
    <thead>
    <tr>
        <th>Primary Domain</th>
        <th>Dedicated IP Address</th>
        <th>Admin Username</th>
        <th>Admin Password</th>
        <th colspan="2">Admin URL</th>
    </tr>
    </thead>
    <tbody>
    {% for cpanelacct in cpanelacct_list %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td><a href="{{ cpanelacct.pk }}/edit/">{{ cpanelacct.domain }}</a></td>
        <td>{{ cpanelacct.ip_addr }}</td>
        <td>{{ cpanelacct.server_username }}</td>
        <td>{{ cpanelacct.server_password }}</td>
        <td><a href="{{ cpanelacct.get_admin_url }}" target="_blank">{{ cpanelacct.get_admin_url }}</a></td>
        <td><form action="https://{{ cpanelacct.domain }}:2083/login/" method="post" target="_top" >
          <input type="hidden" name="login_theme" value="cpanel" />
          <input type="hidden" name="user" id="user" value="{{ cpanelacct.server_username }}" />
          <input type="hidden" name="pass" id="pass" value="{{ cpanelacct.server_password }}" />
          <!-- <input type="hidden" name="goto_uri" value="/?" /> -->
          <input type="submit" value="Login" />
        </form></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
    <p>No Web Hosting Accounts have been created</p>
{% endif %}
{% endblock %}

templates/portal/dashboard.html
{% extends "base_site.html" %}
{% load currency_formatting %}
{% block title %}Account Profile for {{ user.get_full_name }}{% endblock %}
{% block extrastyle %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/portal.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/forms.css" />
<style type="text/css">
  .form-row label { display: none; }
  .form-row textarea,
  .form-row input[type=text],
  .form-row select { width: 250px; }
</style>
{% endblock %}

{% block content_title %}Account Dashboard{% endblock %}
{% block content %}
<div id="dashboard">
<div class="primary-left">
  <table class="width-100">
    <caption>Account Info</caption>
    <tr class="row1">
        <th class="width-40">Name</th>
        <td>{{ user.get_full_name }}</td>
    </tr>
    <tr class="row2">
        <th>Email</th>
        <td>{{ user.email }}</td>
    <tr class="row1">
        <th>Account Number</th>
        <td>{{ user.id }}</td>
    </tr>
    <tr class="row2">
        <th>Last Login</th>
        <td>{{ user.last_login }} [<a href="/accounts/login-history/">view history</a>]</td>
    {% if voip_stats %}
    <tr class="row1">
        <th>Endpoints</th>
        <td>{{ voip_stats.ep_count }} [<a href="/accounts/endpoint/">manage</a>]</td>
    </tr>
    <tr class="row2">
        <th>Active Registrations</th>
        <td>{{ voip_stats.reg_count }} [<a href="/accounts/interconnection/">details</a>]</td>
    </tr>
    {% endif %}
  </table>
  {% if voip_stats %}
  <table class="width-100">
    <caption>Voice Statistics</caption>
    <tbody>
    <tr class="row1">
        <th rowspan="2" class="width-40">Past 12 Hours:</th>
        <td><strong>{{ voip_stats.12h_calls }}</strong> calls</td>
    <tr class="row1">
        <td><strong>{{ voip_stats.12h_mins }}</strong> minutes</td>
    </tr>
    <tr class="row2">
        <th rowspan="2">Three Days:</th>
        <td><strong>{{ voip_stats.3d_calls }}</strong> calls</td>
    <tr class="row2">
        <td><strong>{{ voip_stats.3d_mins }}</strong> minutes</td>
    </tr>
    <tr class="row1">
        <th rowspan="2">Week:</th>
        <td><strong>{{ voip_stats.week_calls }}</strong> calls</td>
    <tr class="row1">
        <td><strong>{{ voip_stats.week_mins }}</strong> minutes</td>
    </tr>
    <tr class="row2">
        <th>Month:</th>
        <td><strong>{{ voip_stats.month_calls }}</strong> calls</td>
    <tr class="row2">
        <th></th>
        <td><strong>{{ voip_stats.month_mins }}</strong> minutes</td>
    </tr>
    </tbody>
    </tr>
  </table>
  {% endif %}
</div>
<div class="secondary-right">
  <div id="balance-cta" class="round right width-100">
    <div id="balance-top" class="round-top">
      <h2>Account Balance</h2>
      <h1>{{ user.get_profile.acct_balance|as_currency }}</h1>
    </div>
    <div id="balance-bottom" class="round-bot">
      <a href="/accounts/billing/payment/">Make a Payment</a>
    </div>
  </div>
  <div id="contact-cta" class="round right width-100">
    <form action="/support/" method="post">{% csrf_token %}
    <input type="hidden" name="name" value="{{ user.get_full_name }}" />
    <input type="hidden" name="username" value="{{ user.username }}" />
    <input type="hidden" name="email" value="{{ user.email }}" />
    <div id="contact-top" class="round-top">
      <h2>Contact Us</h2>
      <div class="form-row">
        <label for="id_subject">Subject</label><span class="form-field"><input name="subject" maxlength="100" placeholder="Brief description of your request" type="text" class="add-ph" id="id_subject" /></span>
      </div>

      <div class="form-row">
        <label for="id_message">Message</label><span class="form-field"><textarea rows="10" name="message" id="id_message" placeholder="Comments" cols="40" class="add-ph"></textarea></span>
      </div>
    </div>
    <div id="contact-bottom" class="round-bot">
      <input type="submit" value="Submit" class="submit-grn" />
    </div>
    </form>
  </div>
</div>
</div>
{% endblock %}
{% block extra_js %}
<script src="{{ STATIC_URL }}js/jquery.addplaceholder.min.js"></script>
<script>
    $('.add-ph').addPlaceholder();
</script>
{% endblock %}

templates/portal/did_form.html
{% extends "base_site.html" %}
{% load cdr_formatting %}
{% block title %}Manage DID{% endblock %}
{% block extrastyle %}
<style type="text/css">
div.form-row { margin-bottom: 12px; }
.form-row textarea,
.form-row input[type="text"],
.form-row input[type="password"],
.form-row select {
    width: 400px;
    padding: 2px 4px;
    border: 1px solid #4f4e4e;
}

#content .container form p { margin: 0 0 16px; }
p.number-info { font-size:16px; }
</style>
{% endblock %}

{% block content_title %}Manage DID{% endblock %}
{% block content %}
<div class="form-row">
  <p class="number-info">Number<br />{{ object.number|num2tel }}</p>
  <p class="number-info">Rate Center<br />{{ object.rate_center }}</p>
</div>
<form action="" method="post">{% csrf_token %}
{% include "form_snippet.html" %}
<input type="submit" value="Submit" />
</form>

{% endblock %}
{% block extra_js %}
<script type="text/javascript">
$(document).ready(function(){
  if ($("input#id_enable_vm").is(':checked')) {
    $('.form-row:has(input#id_vm_to_email)').show();
    $('.form-row:has(input#id_vm_keep_after_email)').show();
    $('.form-row:has(input#id_vm_email)').show();
    $('.form-row:has(select#id_vm_ring_msec)').show();
  } else {
    $('.form-row:has(input#id_vm_to_email)').hide();
    $('.form-row:has(input#id_vm_keep_after_email)').hide();
    $('.form-row:has(input#id_vm_email)').hide();
    $('.form-row:has(select#id_vm_ring_msec)').hide();
  }

  if ($("input#id_enable_fax_srv").is(':checked')) {
    $('.form-row:has(input#id_fax_email)').show();
  } else {
    $('.form-row:has(input#id_fax_email)').hide();
  }

  $("input#id_enable_vm").change(function() {
    if ($("input#id_enable_vm").is(':checked')) {
      $('.form-row:has(input#id_vm_to_email)').show();
      $('.form-row:has(input#id_vm_keep_after_email)').show();
      $('.form-row:has(input#id_vm_email)').show();
      $('.form-row:has(select#id_vm_ring_msec)').show();
    } else {
      $('.form-row:has(input#id_vm_to_email)').hide();
      $('.form-row:has(input#id_vm_keep_after_email)').hide();
      $('.form-row:has(input#id_vm_email)').hide();
      $('.form-row:has(select#id_vm_ring_msec)').hide();
    }
  });

  $("input#id_enable_fax_srv").change(function() {
    if ($("input#id_enable_fax_srv").is(':checked')) {
      $('.form-row:has(input#id_fax_email)').show();
    } else {
      $('.form-row:has(input#id_fax_email)').hide();
    }
  });
});
</script>
{% endblock %}

templates/portal/did_list.html
{% extends "base_site.html" %}
{% load icons %}
{% load cdr_formatting %}

{% block title %}DIDs{% endblock %}
{% block content_title %}DIDs{% endblock %}
{% block content %}
<form method="get" action="/accounts/dids/search/">
  <div id="did-search" class="round">
    <ul>
        <li>
            <input type="text" name="q" placeholder="Search" />
        </li>
        <li>
            <input class="search" type="submit" value="Search" />
        </li>
    </ul>
  </div>
</form>
<a href="purchase/">Purchase</a> | <a href="export/">Export</a>
{% if did_list %}
<table class="width-100">
    <caption>Numbers</caption>
    <thead>
    <tr>
        <th>Number<a href="?order_by=-number" class="sort-icon"><img src="{{ STATIC_URL }}/img/icon_sort.png" /></a></th>
        <th>Endpoint<a href="?order_by=-endpoint" class="sort-icon"><img src="{{ STATIC_URL }}/img/icon_sort.png" /></a></th>
        <th>CNAM<a href="?order_by=-enable_cnam" class="sort-icon"><img src="{{ STATIC_URL }}/img/icon_sort.png" /></a></th>
        <th>Fax Server<a href="?order_by=-enable_fax_srv" class="sort-icon"><img src="{{ STATIC_URL }}/img/icon_sort.png" /></a></th>
        <th>Routing</th>
        <th>Description<a href="?order_by=-description" class="sort-icon"><img src="{{ STATIC_URL }}/img/icon_sort.png" /></a></th>
    </tr>
    </thead>
    <tbody>
    {% for did in did_list %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td><a href="{{ did.get_absolute_url }}">{{ did.number|num2tel }}</a></td>
        <td>{{ did.endpoint|truncatewords:4 }}</td>
        <td>{{ did.enable_cnam|boolean_icon }}</td>
        <td>{{ did.enable_fax_srv|boolean_icon }}</td>
        <td>{{ did.route }}</td>
        <td>{{ did.description|truncatechars:35 }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
    <p>No DIDs have been added</p>
{% endif %}
{% endblock %}

templates/portal/did_prefix_list.html
<table id=did-numbers">
  <caption>Available Numbers</caption>
  <tr>
    <th>DID</th>
    <th>Rate Center</th>
    <th>Cost</th>
    <th>Setup</th>
    <th>Purchase</th>
  </tr>
  {% for did in did_list %}
  <tr>
    <td>{{ did }}</td>
    <td>{{ did.rate_center }}</td>
    <td>${{ did.billing_plan.monthly_price }}/mo</td>
    <td>${{ did.billing_plan.setup_fee }}</td>
    <td><a href="{{ did.get_absolute_url }}purchase/">Purchase</a></td>
  </tr>
  {% endfor %}
</table>

templates/portal/did_purchase.html
{% extends "base_site.html" %}
{% block title %}Purchase DIDs{% endblock %}

{% block content_title %}Purchase DIDs{% endblock %}
{% block content %}
<h1>Purchase Single Telephone Numbers</h1>

<div id="area-list">
    <span>1 - </span>
    <select id="area-code" name="area-code">

    </select>
    <span> - </span>
</div>

<div id="prefix-list">
<form action="" method="post" accept-charset="utf-8">{% csrf_token %}
    <select id="prefix" name="prefix">

    </select>
</form>
<span>- XXXX</span>
</div>
<div id="did-list" class="primary-left">
</div>

{% endblock %}
{% block extra_js %}<script type="text/javascript" src="{{ STATIC_URL }}js/didpurchase.js"></script>{% endblock %}