system/urls.py
from django.conf.urls import patterns, url

from views import *

urlpatterns = patterns('system.views',
    url(r'^gateway-ips/$', 'gw_auth_ip_list_view'),
    url(r'^gateway-ips/add/$', 'gw_auth_ip_create_view'),
    url(r'^gateway-ips/(?P<pk>\d+)/edit/$', 'gw_auth_ip_update_view'),
    url(r'^gateway-ips/(?P<pk>\d+)/delete/$', 'gw_auth_ip_delete_view'),
    url(r'^gateways/$', DrGatewayListView.as_view()),
    url(r'^gateways/add/$', DrGatewayCreateView.as_view()),
    url(r'^gateways/(?P<pk>\d+)/edit/$', DrGatewayUpdateView.as_view()),
    url(r'^gateways/(?P<pk>\d+)/delete/$', DrGatewayDeleteView.as_view()),
    url(r'^routes/$', 'dr_rule_list_view'),
    url(r'^routes/add/$', 'dr_rule_create_view'),
    url(r'^routes/(?P<pk>\d+)/edit/$', 'dr_rule_update_view'),
    url(r'^routes/(?P<pk>\d+)/delete/$', 'dr_rule_delete_view'),
)

urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

from web.views import (DomainFormView, SupportFormView)

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'web.views.index_view'),
    url(r'^about/$', 'web.views.about_view'),
    url(r'^about/network/$', 'web.views.network_view'),
    url(r'^accounts/', include('portal.urls')),
    url(r'^admin/', include('admin.urls')),
    url(r'^contact/$', 'web.views.contact_view'),
    url(r'^contact/done/$', 'web.views.contact_done_view'),
    url(r'^cdr/import/$', 'cdr.views.cdr_import'),
    url(r'^cnam/(?P<number>[2-9]\d\d[2-9]\d{6})/$', 'cnam.views.query'),
    url(r'^crm/phone-lookup/(?P<number>\d{11,16})/$', 'cnam.views.cust_lookup'),
    url(r'^domains/check/', DomainFormView.as_view()),
    url(r'^fax/', include('fax.urls')),
    url(r'^fs-xml/', include('fs_xml_curl.urls')),
    url(r'^kb/', include('kb.urls')),
    url(r'^legal/terms-of-use/$',
        TemplateView.as_view(template_name='terms.html')),
    url(r'^legal/privacy/$',
        TemplateView.as_view(template_name='privacy.html')),
    url(r'^rates/', include('rating.urls')),
    url(r'^services/$', 'web.views.services_view'),
    url(r'^voip-pbx-hosting/$', 'web.views.pbx_service_view'),
    url(r'^web-hosting/$', 'web.views.hosting_service_view'),
    url(r'^sip-trunking/$', 'web.views.services_trunking_view'),
    url(r'^signup/', include('web.registration_urls')),
    url(r'^support/$', SupportFormView.as_view()),
    url(r'^sitemap\.xml$', 'web.views.sitemap_view'),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('',
    url(r'^kb\.php$', RedirectView.as_view(url='/kb/')),
    url(r'^helpdesk\.php$', RedirectView.as_view(url='/support/')),
    url(r'^cart\.php$', RedirectView.as_view(url='/')),
    url(r'^index\.php$', RedirectView.as_view(url='/')),
    url(r'^transcheck\.php$', RedirectView.as_view(url='/')),
    url(r'^aLogin\.php$', RedirectView.as_view(url='/accounts/login/')),
    url(r'^LostPassword\.php$', RedirectView.as_view(url='/accounts/password-reset/')),
    url(r'^contact\.php$', RedirectView.as_view(url='/contact/')),
    url(r'^terms\.php$', RedirectView.as_view(url='/legal/terms-of-use/')),
    url(r'^support\.php$', RedirectView.as_view(url='/support/')),
    url(r'^check\.php$', RedirectView.as_view(url='/web-hosting/')),
    url(r'^hosting\.php$', RedirectView.as_view(url='/web-hosting/')),
    url(r'^forsale\.php$', RedirectView.as_view(url='/web-hosting/')),
    url(r'^hsignup\.php$', RedirectView.as_view(url='/signup/')),
    url(r'^createacct\.php$', RedirectView.as_view(url='/signup/')),
    url(r'^network\.php$', RedirectView.as_view(url='/about/network/')),
)

system/models.py
from django.db import models

import os


class DbBackup(models.Model):
    time_stamp = models.DateTimeField(editable=False)
    file_path = models.CharField(max_length=255, editable=False)

    class Meta:
        ordering = ['id']

    def __unicode__(self):
        return "Database Backup: %s" % self.time_stamp

    def delete(self, *args, **kwargs):
        os.remove(self.file_path)
        super(DbBackup, self).delete(*args, **kwargs)


class DrGateways(models.Model):
    gwid = models.AutoField(primary_key=True)
    type = models.IntegerField(default=0)
    address = models.CharField(max_length=128)
    strip = models.IntegerField(default=0)
    pri_prefix = models.CharField(max_length=64, blank=True, null=True)
    attrs = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=128)

    class Meta:
        ordering = ['gwid']
        db_table = 'dr_gateways'

    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return "/admin/system/gateways/%s/" % self.pk


class DrRules(models.Model):
    RULE_CHOICES = (
        ('1', 'North America'),
        ('2', 'International'),
        ('3', 't.38 Fax'),
    )

    ruleid = models.AutoField(primary_key=True)
    groupid = models.CharField(max_length=255, choices=RULE_CHOICES)
    prefix = models.CharField(max_length=64)
    timerec = models.CharField(max_length=255)
    priority = models.IntegerField(default=1)
    routeid = models.CharField(max_length=64)
    gwlist = models.CharField(max_length=255)
    description = models.CharField(max_length=128, blank=True)

    class Meta:
        ordering = ['ruleid']
        db_table = 'dr_rules'

    def get_absolute_url(self):
        return "/admin/system/routes/%s/" % self.pk

    def get_drgateways(self):
        gwid_list = self.gwlist.split(',')
        drgateway_list = []
        for gw in gwid_list:
            gwid = int(gw.strip())
            drgateway_list.append(DrGateways.objects.get(pk=gwid))
        return drgateway_list

class DrGwLists(models.Model):
    gwlist = models.CharField(max_length=255)
    description = models.CharField(max_length=128, blank=True)

    class Meta:
        ordering = ['id']
        db_table = 'dr_gw_lists'


class DrGroups(models.Model):
    username = models.CharField(max_length=64)
    domain = models.CharField(max_length=128, blank=True)
    groupid = models.IntegerField()
    description = models.CharField(max_length=128, blank=True)

    class Meta:
        ordering = ['id']
        db_table = 'dr_groups'


class GwAuthIP(models.Model):
    grp = models.IntegerField(default=1)
    ip_addr = models.IPAddressField(unique=True)
    mask = models.IntegerField(default=32)
    port = models.IntegerField(default=0)
    tag = models.CharField(max_length=64, blank=True, null=True)
    description = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        ordering = ['ip_addr']
        db_table = 'gw_auth_ip'

    def __unicode__(self):
        return self.ip_addr

    def get_absolute_url(self):
        return "/admin/system/gateway-ips/%s/" % self.pk

system/forms.py
from django import forms
from models import DrGateways, DrRules, GwAuthIP


class DrGatewayForm(forms.ModelForm):
    class Meta:
        model = DrGateways


class DrRuleForm(forms.ModelForm):

    #GWLIST_CHOICES = [(gw.pk, str(gw)) for gw in DrGateways.objects.all()]

    prefix = forms.RegexField(label="Prefix", max_length=16, regex=r'^\d+$',
        help_text = "Required.  16 digits or fewer.",
        error_messages = {'invalid': "This value may contain only numbers"})
    gwlist = forms.CharField(label="Gateway List", max_length=255)

    class Meta:
        model = DrRules
        fields = ("groupid", "prefix", "gwlist", "description",)


class GwIPForm(forms.ModelForm):
    class Meta:
        model = GwAuthIP
        fields = ("ip_addr", "port", "description",)

system/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from forms import DrGatewayForm, DrRuleForm, GwIPForm
from base_views.staff import (StaffCreateView, StaffDeleteView,
                              StaffListView, StaffUpdateView)
from models import DrGateways, DrRules, GwAuthIP
from utils.kamailio import KamailioServer


class AddressReloadListView(StaffListView):

    success_url = None

    def get_success_url(self):
        if self.success_url:
            url = self.success_url
        else:
            raise ImproperlyConfigured(
                "No URL to redirect to. Provide a success_url.")
        return url

    def post(self, request, *args, **kwargs):
        for ip in settings.SIP_PROXY_IPS:
            kam = KamailioServer(ip)
            kam.address_reload()
        return HttpResponseRedirect(self.get_success_url())


class DrReloadListView(StaffListView):

    success_url = None

    def get_success_url(self):
        if self.success_url:
            url = self.success_url
        else:
            raise ImproperlyConfigured(
                "No URL to redirect to. Provide a success_url.")
        return url

    def post(self, request, *args, **kwargs):
        for ip in settings.SIP_PROXY_IPS:
            kam = KamailioServer(ip)
            kam.dr_reload()
        return HttpResponseRedirect(self.get_success_url())

class DrRuleCreateView(StaffCreateView):

    def get_context_data(self, *args, **kwargs):
        context = super(DrRuleCreateView, self).get_context_data(*args, **kwargs)
        context['drgateway_list'] = DrGateways.objects.all()
        return context


class DrRuleUpdateView(StaffUpdateView):

    def get_context_data(self, *args, **kwargs):
        context = super(DrRuleUpdateView, self).get_context_data(*args, **kwargs)
        context['drgateway_list'] = DrGateways.objects.all()
        return context


class DrGatewayCreateView(StaffCreateView):

    form_class = DrGatewayForm
    model = DrGateways
    success_url = "/admin/system/gateways/"
    template_name = "system/dr_gw_form.html"


class DrGatewayUpdateView(StaffUpdateView):

    form_class = DrGatewayForm
    model = DrGateways
    success_url = "/admin/system/gateways/"
    template_name = "system/dr_gw_form.html"


class DrGatewayDeleteView(StaffDeleteView):
    pass


class DrGatewayListView(StaffListView):

    model = DrGateways
    context_object_name = "gw_list"
    template_name = "system/dr_gw_list.html"


dr_rule_list_view = DrReloadListView.as_view(
                            model=DrRules,
                            context_object_name="rule_list",
                            success_url="/admin/system/routes/",
                            template_name="system/dr_rule_list.html")
dr_rule_create_view = DrRuleCreateView.as_view(
                            form_class=DrRuleForm,
                            model=DrRules,
                            success_url="/admin/system/routes/",
                            template_name="system/dr_rule_form.html")
dr_rule_update_view = DrRuleUpdateView.as_view(
                            form_class=DrRuleForm,
                            model=DrRules,
                            success_url="/admin/system/routes/",
                            template_name="system/dr_rule_form.html")
dr_rule_delete_view = StaffDeleteView.as_view(
                            model=DrRules,
                            success_url="/admin/system/routes/",
                            template_name="admin/confirm_delete.html")

gw_auth_ip_list_view = AddressReloadListView.as_view(
                            model=GwAuthIP,
                            context_object_name="gw_ip_list",
                            success_url="/admin/system/gateway-ips/",
                            template_name="system/gw_ips.html")
gw_auth_ip_create_view = StaffCreateView.as_view(
                            form_class=GwIPForm,
                            model=GwAuthIP,
                            success_url="/admin/system/gateway-ips/",
                            template_name="system/gw_ip_form.html")
gw_auth_ip_update_view = StaffUpdateView.as_view(
                            form_class=GwIPForm,
                            model=GwAuthIP,
                            success_url="/admin/system/gateway-ips/",
                            template_name="system/gw_ip_form.html")
gw_auth_ip_delete_view = StaffDeleteView.as_view(
                            model=GwAuthIP,
                            success_url="/admin/system/gateway-ips/",
                            template_name="system/confirm_delete.html")

templates/system/dr_gw_form.html
{% extends "admin_base.html" %}

{% block title %}Edit Gateway{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/system/dr_gw_list.html
{% extends "admin_base.html" %}

{% block title %}SIP Gateways{% endblock %}
{% block content_title %}SIP Gateways{% endblock %}
{% block content %}
{% if gw_list %}
<table>
    <tr>
        <th>Gateway ID</th>
        <th>Gateway Type</th>
        <th>Address</th>
        <th>Strip</th>
        <th>Prefix</th>
        <th>Description</th>
    </tr>
    {% for gw in gw_list %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td><a href="{{ gw.get_absolute_url }}edit/">{{ gw.pk }}</a></td>
        <td>{{ gw.type }}</td>
        <td>{{ gw.address }}</td>
        <td>{{ gw.strip }}</td>
        <td>{{ gw.pri_prefix }}</td>
        <td>{{ gw.description }}</td>
    </tr>
    {% endfor %}
</table>

{% else %}
    <p>No gateways have been created</p>
{% endif %}
<br />
<form action="" method="post">{% csrf_token %}
<input type="submit" value="Reload" />
</form>
{% endblock %}

templates/system/dr_rule_form.html
{% extends "admin_base.html" %}

{% block title %}Edit Routing Rule{% endblock %}
{% block content_title %}Edit Routing Rule{% endblock %}
{% block content %}
<h3>Available Gateways</h3>
<ul>
  {% for gw in drgateway_list %}<li>{{ gw.pk }} - {{ gw }}</li>
  {% endfor %}
</ul>
<br />
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/system/dr_rule_list.html
{% extends "admin_base.html" %}

{% block title %}Routing Rules{% endblock %}

{% block content %}
{% if rule_list %}
<table>
  <tr>
    <th>Rule ID</th>
    <th>Group</th>
    <th>Prefix</th>
    <th>Gateway List</th>
    <th>Description</th>
  </tr>
  {% for rule in rule_list %}
  <tr class="{% cycle 'row1' 'row2' %}">
    <td><a href="{{ rule.get_absolute_url }}edit/">{{ rule.pk }}</a></td>
    <td>{{ rule.get_groupid_display }}</td>
    <td>{{ rule.prefix }}</td>
    <td>{{ rule.gwlist }}</td>
    <td>{{ rule.description }}</td>
  </tr>
  {% endfor %}
</table>

{% else %}
    <p>No rules have been created</p>
{% endif %}
<br />
<form action="" method="post">{% csrf_token %}
<input type="submit" value="Reload" />
</form>
{% endblock %}

templates/system/gw_ip_form.html
{% extends "admin_base.html" %}

{% block title %}Inbound Authorized IP{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/system/gw_ips.html
{% extends "admin_base.html" %}

{% block title %}Inbound Gateway IPs{% endblock %}
{% block content_title %}Inbound Gateway IPs{% endblock %}
{% block content %}
{% if gw_ip_list %}
    <table>
    <tr>
        <th>IP Address</th>
        <th>Port</th>
        <th>Description</th>
    </tr>
    {% for gw_ip in gw_ip_list %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td><a href="{{ gw_ip.get_absolute_url }}edit/">{{ gw_ip }}</a></td>
        <td>{{ gw_ip.port }}</td>
        <td>{{ gw_ip.description }}</td>
    </tr>
    {% endfor %}
    </table>

{% else %}
    <p>No IPs have been created</p>
{% endif %}
<br />
<form action="" method="post">{% csrf_token %}
<input type="submit" value="Reload" />
</form>
{% endblock %}